### ISSUE TITLE
Two specs fail locally, but not on CI

### ISSUE THREAD

**Issue by krisleech** [krisleech/wisper-rspec#3]
![screen shot 2015-01-12 at 09 31 40](https://cloud.githubusercontent.com/assets/66143/5701019/0435d942-9a3e-11e4-9436-8f7c8ce0d74d.png)

**Comment by krisleech** [comment]
@GAV1N Any ideas?

**Comment by GAV1N** [comment]
@krisleech I get those errors when running `bundle exec rspec spec`, but `rspec spec` works fine. Looks like instead of loading the `Wisper::RSpec::BroadcastMatcher` module defined in this gem, Bundler is loading that module of the same name from the wisper gem, and that matcher doesn't support multiple arguments.

Changing [`wisper/rspec/matchers`](https://github.com/krisleech/wisper-rspec/blob/master/spec/wisper/rspec/matchers_spec.rb#L1) to `require File.expand_path('../../../../lib/wisper/rspec/matchers', __FILE__)` did the trick for me. I created a PR with this tweak: https://github.com/krisleech/wisper-rspec/pull/4.

**Comment by krisleech** [comment]
Strange, the PR is much appreciated - thanks :)

**Comment by GAV1N** [comment]
No problem!
